/* Generated By:JavaCC: Do not edit this line. MainConstants.java */
package calculatrice;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MainConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 4;
  /** RegularExpression Id. */
  int LETTRE = 5;
  /** RegularExpression Id. */
  int EOL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<WORD>",
    "<LETTRE>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
  };

}
